spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/userservice #postgres is DB_name
    username: userservice
    password: mysecretpassword
  jpa:
    properties:
      hibernate:
        temp:
          :use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    discovery:
      enabled: false
