version: '3.9'

services:
  user-service:
    image: postgres
    deploy:
      resources:
        limits:
          memory: 200M
    env_file:
      - .env  # Use the .env file for environment variables
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - backend
    volumes:
      - general_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  general_data:

networks:
  backend: